# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff609412078ffcf77f515555ee69c9cc3603bf0774c9b510e3ceae64540205a7052b227e36cec693a09d902a728133a1e54be0fee1bf36eff122399ac18f48db

test:
  secret_key_base: e7ebc020b03a72e1d6fa49edf27d5fe73bf11168973af7ce55607a4e25a26873cc591abedf5f5ae0c056900d69e74ab3fa1b37b18053509ece7ab76e34b8c8cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
